name: Deploy to Packagist

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.0"
                  extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite

            - name: Install dependencies
              run: composer install --no-dev --optimize-autoloader

            - name: Validate composer.json
              run: composer validate

            - name: Check for security vulnerabilities
              run: composer audit --format=json --no-interaction || true

    publish-to-packagist:
        name: publish
        runs-on: ubuntu-latest
        needs: deploy

        steps:
            - uses: actions/checkout@v4

            - name: Publish to Packagist
              run: |-
                  curl --fail-with-body -X POST -H 'Content-Type: application/json' "https://packagist.org/api/update-package?username=${PACKAGIST_USERNAME}&apiToken=${PACKAGIST_API_KEY}" -d '{"repository":"https://www.github.com/infisical/php-sdk"}'
              env:
                  PACKAGIST_USERNAME: ${{ secrets.PACKAGIST_USERNAME }}
                  PACKAGIST_API_KEY: ${{ secrets.PACKAGIST_API_KEY }}
